### ISSUE TITLE
Add method to create shopToken

### ISSUE THREAD

**Issue by ghost** [Labs64/NetLicensingClient-python#1]
_"Create Shop Token"_ is one of the [essential](https://netlicensing.io/wiki/restful-api#essentials) NetLicensing RESTful API methods and need to be enabled as well.

**Comment by ankitsridhar16** [comment]
Can you provide more details for the issue ?

**Comment by r-brown** [comment]
Apologies for the confusion!
This issue is too specific and highly dependent on the issue _Port NetLicensing Java Client library to Python_ #3

Closing this issue as this will be continued by #3
