### ISSUE TITLE
update the tokes value on python

### ISSUE THREAD

**Issue by IAGirl-dev** [Labs64/NetLicensingClient-python#5]
hello, i'd like to know if it is possible to change the tokes value, after the user utilization ( in python) , am trying to develop a softwere where the price of the subcription is based on the number of images that i modify for the user, after identification and extracting the value of the toke that the user get from it subsription how could I update it please?

**Comment by r-brown** [comment]
Hello @IAGirl-dev 
You can use this [community support tracker](https://github.com/Labs64/NetLicensing-Community) to report bugs and to request and vote for new NetLicensing features, as well as collaborate, asking questions around license management and support new NetLicensing adopters.

**Comment by r-brown** [comment]
Generated via [RESTApi tokens](https://netlicensing.io/wiki/token-services#create-token) cannot be changed anymore and usually have short-living expiration.
However, to achieve your requirements, you can use [Pay-per-Use](https://netlicensing.io/wiki/pay-per-use) licensing model.
